const MEBIBYTE = 1024 * 1024;
const MULTIPART_OVERHEAD_MIB = 5;

export const MAX_AUDIO_UPLOAD_FILE_MIB = 150;
export const MAX_AUDIO_STORAGE_OBJECT_MIB = 50;
export const AUDIO_UPLOAD_CHUNK_MIB = 45;
export const MAX_AUDIO_UPLOAD_FILE_BYTES =
  MAX_AUDIO_UPLOAD_FILE_MIB * MEBIBYTE;
export const MAX_AUDIO_STORAGE_OBJECT_BYTES =
  MAX_AUDIO_STORAGE_OBJECT_MIB * MEBIBYTE;
export const AUDIO_UPLOAD_CHUNK_BYTES = AUDIO_UPLOAD_CHUNK_MIB * MEBIBYTE;
export const MAX_AUDIO_UPLOAD_REQUEST_BYTES =
  MAX_AUDIO_UPLOAD_FILE_BYTES + MULTIPART_OVERHEAD_MIB * MEBIBYTE;
export const MAX_AUDIO_UPLOAD_LABEL = `${MAX_AUDIO_UPLOAD_FILE_MIB}MB`;
export const NEXT_MIDDLEWARE_CLIENT_MAX_BODY_SIZE = "160mb";

export function getAudioUploadTooLargeMessage(subject = "파일") {
  return `${subject} 크기가 너무 큽니다. 최대 ${MAX_AUDIO_UPLOAD_LABEL}까지 업로드할 수 있습니다.`;
}
